### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by TheJulianJES** [Qmunity/QmunityLib#3]
Version: QmunityLib-1.7.10-0.1.78-universal.jar
Crash: http://pastebin.com/YgeVBfHW on Server
What did you expect to happen: The server starts
What happened instead: It crashes

**Comment by GirafiStudios** [comment]
What version of Qmunity Lib do you get this on ? :)

**Comment by TheJulianJES** [comment]
Well, a new handcrafted version ;)

**Comment by GirafiStudios** [comment]
QmunityLib-1.7.10-0.1.78-universal ? :)

**Comment by TheJulianJES** [comment]
A self-compiled version, this crash is also in the latest curse version

**Comment by Quetzi** [comment]
we don't accept reports from custom compiles for obvious reasons.

**Comment by TheJulianJES** [comment]
Since I said the crash is also in the latest curse version.

**Comment by Quetzi** [comment]
Either way, I suggest you read/re-read the README.md so that you can report issues properly going forward.

**Comment by TheJulianJES** [comment]
@Quetzi I'm sorry.

**Comment by GirafiStudios** [comment]
Hmm, weird. I don't get this crash with only BluePower, QmunityLIb and Forge Multipart installed :/

**Comment by TheJulianJES** [comment]
It's a server crash.

**Comment by GirafiStudios** [comment]
I tested it on a server.. :3

**Comment by TheJulianJES** [comment]
@GirafiStudios Really?! It dosen't even work if I just install QmunityLib on a server.. :D

**Comment by GirafiStudios** [comment]
Weird o.O Is it a dedicated server, or on your own computer?

**Comment by TheJulianJES** [comment]
My own pc.

**Comment by TheJulianJES** [comment]
My client works fine.

**Comment by modmuss50** [comment]
That is very weird, because EntityClientPlayerMP is not even imported in that class.

**Comment by TheJulianJES** [comment]
Yeah, I already check it.

**Comment by TheJulianJES** [comment]
But it's only with QmunityLib

**Comment by modmuss50** [comment]
Its working fine in my dev env, with and without FMP

**Comment by modmuss50** [comment]
That crash error cannot just be QLib becuase it is being called  at codechicken.multipart.MultiPartRegistry. Try updating FMP?

**Comment by GirafiStudios** [comment]
He's using the latest version of FMP

**Comment by TheJulianJES** [comment]
Yep ;)

**Comment by TheJulianJES** [comment]
I think it was maybe fixed, thanks to @Quetzi but now there is another crash, but I'm closing this now.

**Comment by Quetzi** [comment]
other crash?

**Comment by TheJulianJES** [comment]
Yeah, hand-crafted BluePower version, if it's on curse I will create a issue :P
