### ISSUE TITLE
Cables/logic blocks not working since 0.1.69

### ISSUE THREAD

**Issue by Firehead94** [Qmunity/QmunityLib#6]
I cant get any cables, logic blocks or machines to work in bluepower when newer versions (1.76 & 1.79 of QmunityLib are installed. 

Using QmunityLib-1.7.10-0.1.69-universal.jar & any beta version of BluePower
http://i.imgur.com/GBa9enU.png

Using QmunityLib-1.7.10-0.1.76-universal.jar & any beta version of BluePower
http://i.imgur.com/hKDqDFM.png

Using QmunityLib-1.7.10-0.1.78-universal.jar & any beta version of BluePower
http://i.imgur.com/GGf82vW.png

**Comment by GirafiStudios** [comment]
This is a known "issue". The problem is that the versions later than version 1.69 is made to work with a newer version of BluePower.
Until BluePower gets updated, use QmunityLib version 1.69 :)

**Comment by Firehead94** [comment]
ah ok, didnt know if it was alright to use newer bluepower with old qmunitylib. Just figured get the ones with the same date release.

**Comment by GirafiStudios** [comment]
Version 1.76 and version 1.78 should not have been released before the new Blue Power version is ready. At least that's my opinion :)

**Comment by amadornes** [comment]
Yeah, 1.76 and 1.79 shouldn't have made it to CurseForge. Luckily we took them down just an hour later so not many people got them, but they're made for the new BP (still unreleased), not the old one :P

**Comment by GirafiStudios** [comment]
@amadornes they are both still on CurseForge tho :p

**Comment by amadornes** [comment]
I thought @Quetzi took them down O_o

**Comment by TheJulianJES** [comment]
@amadornes They're still on ;)

**Comment by amadornes** [comment]
This was fixed with the release Q pushed last week :P

**Comment by TheJulianJES** [comment]
@amadornes It was, but the broken versions are still on :P
