### ISSUE TITLE
forge multipart incompatibility crash

### ISSUE THREAD

**Issue by zortag** [Qmunity/QmunityLib#8]
http://pastebin.com/THHuQzpD
the world is not corrupted, but looking at a bluepower freestanding red alloy wire with any forge multipart microblock in hand generate this crash. tested with some microblocks but only with that wire.
when reloading the world is at a moment before i'll looking the wire.

**Comment by Quetzi** [comment]
Does this still happen with the latest QmunityLib on curse? (114)

**Comment by amadornes** [comment]
Update QLib. A fix for this was released the other day.

**Comment by zortag** [comment]
thanks, it works now
